### ISSUE TITLE
Type "All Blog category(ies)" does not populate dropdown with CMS pages to choose from

### ISSUE THREAD

**Issue by CptMeatball** [rainlab/sitemap-plugin#23] opened 2015-09-17 20:11 UTC
The documentation states that the dropdown in the "blog categories" type, refers to all the cms pages that have the component "blogPosts" implemented. I do have the page, only it does not populate said dropdown. 

Is there something I'm missing, or is this a bug?

**Comment by bakerstreetsystems** [comment] 2016-03-12 03:27
I'm having the same issue.

![screen shot 2016-03-11 at 8 26 14 pm](https://cloud.githubusercontent.com/assets/5008697/13720497/b13b2192-e7c7-11e5-8e71-0f55a986dfe6.png)

**Comment by vojtasvoboda** [comment] 2016-03-12 12:16
I sent pull request for that 2 months ago: https://github.com/rainlab/blog-plugin/pull/167

**Comment by JumpLink** [comment] 2016-06-21 10:05
I have the same issue.

**Comment by PhilMarc** [comment] 2016-08-21 11:35
+1

**Comment by daftspunk** [comment] 2016-08-24 08:43
Duplicate of https://github.com/rainlab/blog-plugin/issues/123
Refs https://github.com/rainlab/pages-plugin/issues/122

**Closed by daftspunk** 2016-08-24 08:43 UTC
