### ISSUE TITLE
cms page - no matches found

### ISSUE THREAD

**Issue by robertrichter** [rainlab/sitemap-plugin#2] opened 2014-11-23 09:13 UTC
Hello,
I tried out the plugin and I would like to add an item related to all blog categories. I have a cms page that shows all blog entries from rainlab - blog. But this page is not in the CMS Page dropdown. Are there some configuration I missed?

Thanks
Rob

**Comment by daftspunk** [comment] 2015-03-14 03:18
Duplicate of #11 

Should be fixed in the next update 1.0.13 of RainLab Blog and Core Build 225

**Closed by daftspunk** 2015-03-14 03:18 UTC

**Comment by ixperiencenl** [comment] 2016-02-10 19:19
Looks like this problem has shown up again in the latest build (1.0.6) with Blog 1.2.2... This is a problem because the blog is important for SEO, can you please fix this?

**Comment by daftspunk** [comment] 2016-02-10 19:24
I have tested this with the `RainLab.Relax` theme and it appears to be working. Perhaps there is some misconfiguration?

**Comment by ixperiencenl** [comment] 2016-02-10 20:43
Thank you, maybe it has something to do with the theme? I've removed and re-installed the blog and the sitemap and vice versa but it just doesn't show the page.  I know it's very hard to find out what's going on when you can't see the site itself. If needed I can provide you with details in private message.
