### ISSUE TITLE
Incorrectly lists the URLs for unpublished blog posts in the sitemap

### ISSUE THREAD

**Issue by jm-mwi** [rainlab/sitemap-plugin#56] opened 2017-11-02 19:02 UTC
The plugin currently adds URLs for blog posts even if they aren't published.

The plugin should either only list the blog posts that are published or it should also add the blog post to the robots file as a URL that shouldn't be visited.

**EDIT:** This is being reported as I'm seeing URL errors show up in my webmaster console.

**Comment by LukeTowers** [comment] 2017-11-02 19:14
@jm-mwi feel free to make a PR that adds the published filtering to the pages.resolveItems handling used by the sitemap generator.

**Comment by LukeTowers** [comment] 2017-11-02 20:31
Duplicate of https://github.com/rainlab/blog-plugin/issues/346

**Closed by LukeTowers** 2017-11-02 20:31 UTC
Labels: Status: Review Needed, Type: Unconfirmed Bug
